name: Python CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    # Add step to install dependencies
    - name: Install dependencies
      run: python -m pip install pytest --upgrade pip setuptools wheel

  lint:
    # Complete the lint job configuration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    # Add step to install dependencies
    - name: Install dependencies
      run: python -m pip install pylint --upgrade pip setuptools wheel
